/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlinkedRouteImport } from './routes/unlinked'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RedemptionsRouteImport } from './routes/redemptions'
import { Route as EarningRouteImport } from './routes/earning'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IssueIdRouteImport } from './routes/issue.$id'

const UnlinkedRoute = UnlinkedRouteImport.update({
  id: '/unlinked',
  path: '/unlinked',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RedemptionsRoute = RedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningRoute = EarningRouteImport.update({
  id: '/earning',
  path: '/earning',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueIdRoute = IssueIdRouteImport.update({
  id: '/issue/$id',
  path: '/issue/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/earning': typeof EarningRoute
  '/redemptions': typeof RedemptionsRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/timeline': typeof TimelineRoute
  '/unlinked': typeof UnlinkedRoute
  '/issue/$id': typeof IssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/earning': typeof EarningRoute
  '/redemptions': typeof RedemptionsRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/timeline': typeof TimelineRoute
  '/unlinked': typeof UnlinkedRoute
  '/issue/$id': typeof IssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/earning': typeof EarningRoute
  '/redemptions': typeof RedemptionsRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/timeline': typeof TimelineRoute
  '/unlinked': typeof UnlinkedRoute
  '/issue/$id': typeof IssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/earning'
    | '/redemptions'
    | '/settings'
    | '/sync'
    | '/timeline'
    | '/unlinked'
    | '/issue/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/earning'
    | '/redemptions'
    | '/settings'
    | '/sync'
    | '/timeline'
    | '/unlinked'
    | '/issue/$id'
  id:
    | '__root__'
    | '/'
    | '/earning'
    | '/redemptions'
    | '/settings'
    | '/sync'
    | '/timeline'
    | '/unlinked'
    | '/issue/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarningRoute: typeof EarningRoute
  RedemptionsRoute: typeof RedemptionsRoute
  SettingsRoute: typeof SettingsRoute
  SyncRoute: typeof SyncRoute
  TimelineRoute: typeof TimelineRoute
  UnlinkedRoute: typeof UnlinkedRoute
  IssueIdRoute: typeof IssueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlinked': {
      id: '/unlinked'
      path: '/unlinked'
      fullPath: '/unlinked'
      preLoaderRoute: typeof UnlinkedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redemptions': {
      id: '/redemptions'
      path: '/redemptions'
      fullPath: '/redemptions'
      preLoaderRoute: typeof RedemptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earning': {
      id: '/earning'
      path: '/earning'
      fullPath: '/earning'
      preLoaderRoute: typeof EarningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue/$id': {
      id: '/issue/$id'
      path: '/issue/$id'
      fullPath: '/issue/$id'
      preLoaderRoute: typeof IssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarningRoute: EarningRoute,
  RedemptionsRoute: RedemptionsRoute,
  SettingsRoute: SettingsRoute,
  SyncRoute: SyncRoute,
  TimelineRoute: TimelineRoute,
  UnlinkedRoute: UnlinkedRoute,
  IssueIdRoute: IssueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
